/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'quantity' : bigint, 'foodItem' : FoodItem }
export interface FoodItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'rating' : number,
  'price' : number,
}
export type OrderStatus = { 'preparing' : null } |
  { 'outForDelivery' : null } |
  { 'orderPlaced' : null } |
  { 'delivered' : null };
export interface OrderType {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'totalAmount' : number,
  'items' : Array<CartItem>,
  'distanceInKm' : number,
}
export interface Subscription {
  'id' : bigint,
  'endDate' : Time,
  'userId' : Principal,
  'plan' : SubscriptionPlan,
  'isActive' : boolean,
  'startDate' : Time,
}
export type SubscriptionPlan = { 'monthlyCombo' : null } |
  { 'monthlyDinner' : null } |
  { 'weeklyDinner' : null } |
  { 'monthlyLunch' : null } |
  { 'weeklyCombo' : null } |
  { 'weeklyLunch' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'savedAddresses' : Array<string>,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodItem' : ActorMethod<[string, string, number, string, string], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getActiveSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getFoodItem' : ActorMethod<[bigint], FoodItem>,
  'getOrder' : ActorMethod<[bigint], OrderType>,
  'getOrderHistory' : ActorMethod<[], Array<OrderType>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, number], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribeToPlan' : ActorMethod<[SubscriptionPlan, Time, Time], bigint>,
  'updateCartItemQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];