/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const SubscriptionPlan = IDL.Variant({
  'monthlyCombo' : IDL.Null,
  'monthlyDinner' : IDL.Null,
  'weeklyDinner' : IDL.Null,
  'monthlyLunch' : IDL.Null,
  'weeklyCombo' : IDL.Null,
  'weeklyLunch' : IDL.Null,
});
export const Subscription = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : Time,
  'userId' : IDL.Principal,
  'plan' : SubscriptionPlan,
  'isActive' : IDL.Bool,
  'startDate' : Time,
});
export const FoodItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'savedAddresses' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'foodItem' : FoodItem,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'orderPlaced' : IDL.Null,
  'delivered' : IDL.Null,
});
export const OrderType = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(CartItem),
  'distanceInKm' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFoodItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getActiveSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getFoodItem' : IDL.Func([IDL.Nat], [FoodItem], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [OrderType], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Nat], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribeToPlan' : IDL.Func([SubscriptionPlan, Time, Time], [IDL.Nat], []),
  'updateCartItemQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const SubscriptionPlan = IDL.Variant({
    'monthlyCombo' : IDL.Null,
    'monthlyDinner' : IDL.Null,
    'weeklyDinner' : IDL.Null,
    'monthlyLunch' : IDL.Null,
    'weeklyCombo' : IDL.Null,
    'weeklyLunch' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : Time,
    'userId' : IDL.Principal,
    'plan' : SubscriptionPlan,
    'isActive' : IDL.Bool,
    'startDate' : Time,
  });
  const FoodItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'savedAddresses' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'foodItem' : FoodItem });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'orderPlaced' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const OrderType = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(CartItem),
    'distanceInKm' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFoodItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getActiveSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getFoodItem' : IDL.Func([IDL.Nat], [FoodItem], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [OrderType], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Nat], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribeToPlan' : IDL.Func([SubscriptionPlan, Time, Time], [IDL.Nat], []),
    'updateCartItemQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };